[package]
name = "fw-logger"
version = "0.1.0"
authors = ["Kailun Qin <kailun.qin@intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x86_64 = "0.14.10"
spin = "0.9.4"
log = "0.4.13"
